world_frame: map
robot_frame: base_footprint
<<<<<<< HEAD
minimum_distance: 1
planner_activation_distance: 2
minimum_planner_distance: 1.5
=======
minimum_distance: 2  
planner_activation_distance: 3
minimum_planner_distance: 2.5
>>>>>>> fd20771ed8257a7896ec17c2a641b2fad3e25b79
