%YAML:1.0
#TODO - VALUES FOR THE GAZEBO CAMERA! 
#The focal length was calculated using: flength = (width/2)/tan(hfov/2)

image_width: 320
image_height: 240
camera_name: gazebo
camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [173.27, 0, 160, 0, 173.27, 120, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [0, 0, 0, 0, 0]
rectification_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  
 #This needs to be calculated... For now it's useless
projection_matrix: !!opencv-matrix
  rows: 3
  cols: 4
  dt: d
  data: [173.27, 0, 160, 0, 0, 173.27, 120, 0, 0, 0, 1, 0]
